// Public, non-personal audit summary. Operational evidence stays in the app workspace.
export const audit = {
  date:'5 October 2026', verdict:'Not production ready',
  scores:[
    ['Authentication',3,'Email confirmation is off; admin MFA and session deadlines are not enforced by the app.'],
    ['Authorization',4,'Live RLS exists, but the stronger field and approval checks remain local.'],
    ['Input validation',5,'New database bounds and upload checks are prepared; live coverage is incomplete.'],
    ['Secrets management',6,'Member source now has a local Git checkpoint and staged-file secret checks; host settings and earlier unversioned changes still need verification.'],
    ['Security headers',4,'The report receives new headers in this release; the member app host is not verified.'],
    ['Rate limiting',3,'Live login limits differ from the requested target; new shared limits are not deployed.'],
    ['Error handling',5,'No tested production incident trail or complete rejection reporting.'],
    ['Dependencies',7,'npm audit found no high/critical advisories; other supply-chain checks remain incomplete.'],
    ['Infrastructure',2,'Member domain, recovery, monitoring and the production rollout remain unresolved.'],
    ['Optional review tools','N/A','The optional review tool is disabled. Approve a budget before enabling it.'],
    ['Observability',2,'No confirmed alert recipient, tested delivery or complete retention schedule.'],
  ],
  blockers:[
    'Verify real email ownership, including accounts created while automatic confirmation was on.',
    'Add administrator MFA enrollment and enforce its second step on the server.',
    'Reconcile and deploy the prepared permission, input and upload safeguards in a test environment first.',
    'Set stronger login protection and protect expensive requests at the gateway.',
    'Define session deadlines, password-change reauthentication and a tested account revocation procedure.',
    'Decide whether profile photos should be private and align the privacy notice with actual storage access.',
    'Confirm the member app domain, HTTPS and release rollback; the configured domain did not resolve during this review.',
    'Complete a backup restoration drill and agree backup, deletion and log retention periods.',
    'Name the incident and cost-alert owner, set a budget, and test alert delivery.',
    'Complete real production integration checks, approved privacy wording and a repeatable release pipeline.',
  ],
  findings:[
    ['Major','Email ownership is not checked','Live setting','Automatic confirmation is enabled. An address being marked confirmed does not prove that its owner received a message.','Configure and test email delivery, enable confirmation and re-verify existing accounts.'],
    ['Critical','An administrator password is still the main gate','Open','The provider supports authenticator codes, but the app has no enrollment/challenge flow and its admin permission checks do not require the second step.','Enroll administrators, implement recovery, then require verified MFA in server permissions.'],
    ['Major','Prepared safeguards are absent from the live backend','Live setting','The two hardening migrations and upload-file function are absent from the live inventory. Existing direct storage policies bypass the planned upload gate.','Coordinate a tested migration, function and client rollout. Do not apply migrations blindly over custom production changes.'],
    ['Major','Session and recovery rules miss the requested standard','Live setting','Absolute and idle session limits are both zero (never). Access tokens last one hour; email links expire at 3,600 seconds, rather than less than an hour.','Agree supported server session deadlines and shorter recovery expiry; test logout and password-change revocation.'],
    ['Major','Login and bot protection need tightening','Live setting','The observed sign-in/sign-up limit is 30 per five minutes per IP. This does not meet five attempts per 15 minutes per IP and address; CAPTCHA is off.','Add a trusted gateway/account-aware control with progressive delay, and test recovery/email limits.'],
    ['Major','Profile photos can be shared outside the app','Live setting','The profile-photo bucket is public. Other file buckets are private, but that does not make avatar links private.','Decide the intended audience, migrate public photo references if needed, and verify unauthenticated access is blocked.'],
    ['Major','Current upload protection is incomplete','Live setting','The announcement bucket has no recorded size/type limit; the media bucket allows video up to 50 MiB. New MIME/signature checks and smaller allowances are not live.','Deploy the mandatory image upload gate, close direct writes and test invalid files plus quota bypass.'],
    ['Major','Logout does not prove immediate server revocation','Open','Local data is cleared immediately, but the remote logout request is best effort. An already-issued bearer token can remain valid until expiry.','Check active sessions for sensitive actions and test failed logout and password-change scenarios on the real provider.'],
    ['Major','An incident may have no confirmed responder or alert','Open','PCEC administrator is agreed as the draft incident owner and a response plan is prepared. A named responder, official recipient, approval, practice exercise and working alert delivery remain pending.','Finalize contacts, approve and rehearse the response plan, then test safe, deduplicated alerts without sending member details or credentials.'],
    ['Major','Recovery from lost data is unproven','Unverified','No restore drill, agreed recovery target or verified backup retention evidence was available.','Restore a backup into a separate environment and record the result before paid launch.'],
    ['Major','Member releases still lack enforced remote checks','Partly addressed','The local deploy script now requires clean committed source, secret/security/browser checks and a bounded website verification after production upload. The member app still has no source remote or active CI; live deployment and rollback are untested.','Choose the member remote, activate required CI and complete the actual host release/rollback drill. A passing website check does not prove email, permissions or recovery.'],
    ['Major','Larger lists need real pagination','Partly addressed','Admin members now use 25-record cursor pages and server-side search, tested with 1,106 sample accounts including timestamp ties. This is not deployed; other fixed-cap lists still lack complete older-record navigation.','Deploy and verify member paging/search on the real provider, then complete the remaining list workflows and verify server limits.'],
    ['Major','The privacy notice contains unresolved commitments','Local fix prepared','The local notice now explains public photo links and removes the unsupported seven-day backup claim. The DPO, retention periods and operational procedure still need approval.','Publish verified contact details, approve accurate wording and test export/deletion handling.'],
    ['Major','The configured member domain is not ready to verify','Unverified','The configured domain failed DNS resolution in this review. The report site and the member app are separate deployments.','Confirm the actual member host, DNS, certificate, redirects and deployed version.'],
    ['Major','The report site lacked browser protection headers','Fixed in this report release','The earlier live response had HSTS but no CSP, nosniff, frame restriction or referrer policy.','Publish the new Vercel headers and external scripts, then verify live responses.'],
    ['Major','A late profile response could restore stale details after logout','Fixed locally','Local session loading now invalidates pending work on logout or account changes, and forced role checks do not reuse a cached profile after failure.','Deploy the tested client; the delayed-response regression test passes.'],
    ['Major','Private image links were cached across account changes','Fixed locally','The local cache now clears on account changes, ignores late results and uses links expiring in five minutes instead of one hour.','Deploy the client. Previously issued links still remain usable until their original expiry.'],
    ['Minor','Account links could retain sensitive URL content','Fixed locally','Partial credential fragments are cleared; arbitrary error descriptions use a fixed message; signup addresses stay in memory instead of URLs. The implicit flow still uses token fragments.','Deploy the fix and plan a tested PKCE flow if the strict no-URL-token requirement must be met.'],
    ['Minor','Service pauses and retry guidance were missing','Fixed locally','Server upload/deletion pause switches and Retry-After headers are prepared. Database-trigger rate failures still need a consistent HTTP 429 response.','Deploy the functions, record how to use the switches, and normalize database rate errors.'],
    ['Minor','A support channel and export workflow are missing','Open','No security.txt contact or authenticated export workflow exists. Account deletion exists, but the hardened version is not deployed.','Choose a real security contact and implement an approved, ownership-checked export and deletion process.'],
    ['Minor','Optional review tool needs a spending limit','Disabled by default','The optional tool has a runtime limit, but no approved budget or provider spending cap. It is separate from member features.','Keep it disabled until its provider budget and runner permissions are reviewed.'],
  ],
  fixes:[
    'Publish and verify report browser-protection headers (prepared).',
    'Deploy the tested logout/profile race fix (prepared).',
    'Deploy private-link cache isolation and shorter expiry (prepared).',
    'Deploy account-link error cleanup (prepared).',
    'Deploy pause switches and retry guidance (prepared).',
    'Remove unsupported privacy promises and confirm the DPO contact.',
    'Assign a security/cost alert owner and a monthly spending ceiling.',
    'Test SMTP and use account email templates in the actual provider.',
    'Enable email confirmation and plan existing-account verification.',
    'Shorten recovery expiry and verify server password requirements.',
    'Connect the local member Git repository to its remote and enforce release checks.',
    'Confirm the member host, DNS, HTTPS and redirect allowlist.',
    'Run a backup restore drill and agree retention periods.',
    'Reconcile production schema and test the prepared migrations.',
    'Deploy upload functions and block the direct-upload bypass together.',
    'Require admin MFA and prepare recovery before enforcement.',
    'Add account-aware login/gateway protection and expensive-request controls.',
    'Enforce session deadlines and immediate revocation for sensitive actions.',
    'Add cursor pagination, private-avatar migration and a safe export workflow.',
    'Test production alerts, retention, rollback and all permission scenarios before paid launch.',
  ],
  days:[
    ['Days 1–2','Owner and operating limits','Confirm the member domain, alert recipient, budget and data-retention owner. Verify repository and provider access.'],
    ['Days 3–4','Recovery and email','Restore a test backup. Verify SMTP, redirects, confirmation and recovery expiry; inventory existing auto-confirmed accounts.'],
    ['Days 5–7','Permissions and uploads','Reconcile custom production migrations in a test environment. Test role changes, hidden data, invalid uploads and the spending limits.'],
    ['Days 8–10','Admin and session security','Add authenticator enrollment/challenge/recovery; require server MFA for admins. Test revocation and stronger bot/login protection.'],
    ['Days 11–12','Operations and privacy','Complete list pagination, approved privacy wording, contact/export procedures and alert delivery.'],
    ['Days 13–14','Controlled release','Perform production integration, rollback and monitoring drills. Release only when blockers have verified evidence.'],
  ],
  checks:[
    ['Authentication & sessions',[
      ['PASS','bcrypt/Argon2 password hashing','Supabase manages bcrypt hashing; the app sends passwords directly to Auth. Provider documentation, not a database-password dump.'],
      ['UNVERIFIED','Server password minimum ≥8','UI requires eight; the live numerical provider minimum was redacted in the accessible settings view.'],
      ['UNVERIFIED','Cryptographic token entropy ≥128 bits','Provider issues tokens. Generation implementation/entropy was not independently measured.'],
      ['FAIL','Absolute and idle session expiry','Live Auth: both limits zero/never, unavailable on current Free plan.'],
      ['FAIL','Logout and password-change invalidation','Logout is local plus best effort; no immediate server-session check or production revocation test.'],
      ['FAIL','Login ≤5 attempts/15 minutes/IP+email','Observed provider limit: 30/5 minutes/IP; account-aware enforcement missing.'],
      ['UNVERIFIED','Lockout or progressive failure delay','Browser traffic cooldown is not a server credential-failure policy.'],
      ['FAIL','Single-use recovery expires <1 hour','Live email expiry is exactly 3,600 seconds; production reuse tests pending.'],
      ['FAIL','No credentials/PII in logs, errors or URLs','Implicit Auth fragments and signed file URLs remain; full infrastructure log review pending.'],
      ['FAIL','Privileged-account MFA','TOTP supported by provider; no app enrollment/challenge or mandatory server admin AAL2 check.'],
      ['UNVERIFIED','Constant-time secret comparisons','Provider handles credentials; no custom app secret comparison found; provider implementation not audited.'],
    ]],
    ['Authorization & access control',[
      ['FAIL','Every API has complete server authorization','Live RLS is on for 16 tables; stronger approval/field guards and updated Edge Functions are not live.'],
      ['FAIL','No unintended unauthenticated access','Profile photos are public; privacy wording described member-only access.'],
      ['FAIL','Admin-only requests reject unauthorized users','Local RLS denial tests pass; live HTTP rejection and privileged-session integration tests pending. RLS may return empty results rather than 401/403.'],
      ['UNVERIFIED','All object ownership / IDOR cases','Local RLS tests cover key cases; full live table, view, RPC and Storage deny matrix not completed.'],
      ['N/A','Multi-tenant isolation','Single PCEC organization; no tenant data model or cross-tenant jobs.'],
      ['FAIL','Centralized permission checks','Shared database helpers exist, but live helper conditions differ from the prepared stricter version.'],
      ['FAIL','Scoped service credentials','The Edge Functions use the broad service-role key; compensate with server checks and narrower service operations.'],
    ]],
    ['Input validation & injection',[
      ['FAIL','All server types, lengths, formats and ranges','Prepared bounds are not live; historical NOT VALID constraints and all format/range rules need review.'],
      ['PASS','Parameterized database access','JSON PostgREST filters and typed RPC arguments; no user-generated SQL concatenation found in reviewed app paths.'],
      ['PASS','No user-input eval/exec/Function','No matching app execution sink; deployment scripts use operator configuration, not web request text.'],
      ['PASS','No unsanitized user-content innerHTML','DOM helper uses text nodes and URL protocol checks; local browser XSS regression passes.'],
      ['FAIL','Private, bounded, verified uploads','Live announcement limit missing, videos allowed, profile bucket public; new magic-byte upload gate remains local.'],
      ['N/A','XML external entity protection','No XML parsing integration found.'],
      ['PASS','No shell built from member request data','No member-request shell handler. Operator deployment fields are now locally validated.'],
      ['N/A','LDAP/NoSQL injection','No LDAP or NoSQL integration found.'],
    ]],
    ['Sensitive data & secrets',[
      ['PASS','No hardcoded private keys in reviewed client','Build permits only public fields and publishable/anon Supabase keys; bundle scan passes. Public keys are intentionally public.'],
      ['PASS','Server secrets use environment/secrets','Edge Functions read server environment; the optional review workflow uses a repository secret.'],
      ['PASS','.env ignored and not committed','Local member Git excludes .env, signing keys, generated outputs and historical private QA notes. Staged-file scan passed.'],
      ['UNVERIFIED','Git history secret scan','Initial member checkpoint scanned; earlier unversioned work has no history to audit. Host credential inventory and exhaustive history review remain open.'],
      ['UNVERIFIED','Sensitive data encrypted at rest','Managed provider and host backup/key settings were not fully inspected. No payment data integration exists.'],
      ['UNVERIFIED','TLS 1.2+ across all service hops','API HTTPS configured; member DNS failed; database/operator TLS policy not verified.'],
      ['FAIL','No sensitive client/URL persistence','No local token persistence in tested build; member data is necessarily displayed in memory, implicit fragments and signed links still exist.'],
      ['PASS','No database connection details in client errors','Client masks server/SQL errors; reviewed code logs fixed failure text. Direct provider response review still needed.'],
      ['UNVERIFIED','No secrets/PII in all logs','App logs use fixed text; host/provider/access-log exports and redaction not audited.'],
    ]],
    ['Security headers & transport',[
      ['UNVERIFIED','HTTP redirects to HTTPS','Report HTTPS works; member host/DNS and exact HTTP redirect behavior need verification.'],
      ['PASS','HSTS ≥31,536,000 seconds on report','Live report had 63,072,000 seconds; member Caddy template is local evidence only.'],
      ['PASS','CSP default-src self on report release','New Vercel config; scripts extracted into same-origin assets. Member deployment still unverified.'],
      ['PASS','nosniff on report release','New Vercel header; mirrored by local preview for testing.'],
      ['PASS','Frame restriction on report release','DENY and CSP frame-ancestors none; member template pending rollout.'],
      ['PASS','Referrer policy on report release','strict-origin-when-cross-origin in new report config.'],
      ['FAIL','Exact CORS on every service','Local Edge allowlist is exact; managed REST CORS remains provider-managed and relies on RLS.'],
      ['N/A','Secure/HttpOnly/SameSite auth cookies','SPA uses in-memory bearer credentials, not application session cookies.'],
      ['FAIL','No session tokens in URLs','Implicit callback uses token fragments; malformed links now cleared locally.'],
    ]],
    ['Rate limiting & abuse prevention',[
      ['FAIL','Limits on all auth/upload/paid endpoints','Provider limits differ from requested policy; new upload/shared server quotas not deployed.'],
      ['FAIL','Both IP and user limits','Prepared user quotas exist; comprehensive gateway/IP protection and denied-request accounting missing.'],
      ['FAIL','Meaningful HTTP 429 Retry-After everywhere','Edge helper fixed locally; database-trigger quota errors still use P0001 rather than HTTP 429.'],
      ['FAIL','No unbounded or incomplete pagination','Member pages/search are bounded and tested locally with 1,106 fixtures. Live rollout, other capped lists and real server limits remain pending.'],
    ]],
    ['Error handling & logging',[
      ['FAIL','No verbose production errors','Local client masks errors and no production maps are built; direct live provider errors not exhaustively inspected.'],
      ['FAIL','Generic users / safe detailed server diagnostics','Function logs contain only fixed failure text, without a useful bounded reason/correlation field.'],
      ['FAIL','Security event coverage','Provider Auth audit logs exist; app permission-denial, upload and cost-event delivery/retention not end-to-end verified.'],
      ['FAIL','Safe timestamp/actor/IP/endpoint/status context','No complete consistent structured incident trail. IP collection/retention requires an approved purpose.'],
      ['FAIL','Defined log retention','No complete provider/host/app retention schedule.'],
      ['FAIL','Unhandled rejections caught and reported','Route/function catches exist; no global monitored rejection handler or proven background-error alert.'],
    ]],
    ['Dependencies & supply chain',[
      ['PASS','npm high/critical audit','Both workspaces: zero npm advisories on audit date. Not a complete supply-chain guarantee.'],
      ['UNVERIFIED','Typosquatting/provenance review','Direct package names checked; every transitive package and Action source not audited.'],
      ['PASS','Committed member lockfiles','npm and Deno lockfiles are in the local member-app checkpoint. Active remote checks still need setup.'],
      ['UNVERIFIED','No unused dependencies','App has development dependencies only; exhaustive transitive reachability not proven.'],
      ['FAIL','Pinned/reviewed external frontend assets','No third-party executable script found; Google Fonts/icon CSS is an external mutable stylesheet.'],
      ['UNVERIFIED','No reachable CVE in any dependency','npm audit found none; Deno, GitHub Actions, Caddy, OS and provider coverage incomplete.'],
    ]],
    ['Infrastructure & deployment',[
      ['UNVERIFIED','Production secrets not in repository','Initial local member checkpoint passed common-secret and private-file checks. Public config uses the intended anon key; host secret inventory is pending.'],
      ['UNVERIFIED','No public debug/dev/admin access','Local build strips maps/dev tools; actual member host and server configuration not inspected. Admin UI is protected, not required to be hidden.'],
      ['FAIL','Database TLS, network and least privilege','Managed Data API intentionally public; RLS is required. Broad client table grants observed; DB network/TLS controls unverified.'],
      ['FAIL','Private storage default / signed access','Profile bucket public; private link cache fixed locally and TTL shortened to five minutes.'],
      ['FAIL','Safe active CI and verified rollback','Member repository is local only, so the prepared CI is inactive. Atomic VPS release/rollback scripts remain untested on the actual host.'],
      ['FAIL','Health check','No dedicated health endpoint or tested end-to-end uptime probe. Static report availability does not prove API health.'],
      ['UNVERIFIED','Graceful shutdown','Static frontend / managed serverless functions; provider deployment lifecycle not verified. No app job queue.'],
      ['FAIL','Automated backups, restore test, retention','No verified restore evidence or approved retention/recovery targets.'],
    ]],
    ['Optional external review',[
      ['N/A','Untrusted integration instructions','No member endpoint accepts external-review instructions. The optional tool only reviews trusted repository changes.'],
      ['N/A','External-review output validation','External review results do not enter member screens or records.'],
      ['FAIL','Optional-service spending ceiling','Optional development Action is disabled; runtime limit is not a dollar cap.'],
      ['N/A','Private review instructions','The member app has no private external-review instructions.'],
      ['UNVERIFIED','Development reviewer execution isolation','GitHub-hosted runner is separate from app server; Action tool permissions and network confinement need review before opt-in.'],
      ['PASS','External-service secret storage','The optional workflow uses GitHub Secrets. Its key is absent from the member build; the tool remains disabled.'],
    ]],
    ['Missing operational systems',[
      ['FAIL','Complete audit trail','Auth provider audit exists; admin content/role changes lack a complete tested app audit trail.'],
      ['FAIL','Uptime/error/latency alerting','No verified configured owner, monitoring or notification test.'],
      ['FAIL','security.txt contact','No published security.txt; real responsible contact not selected.'],
      ['FAIL','Approved privacy and terms','Pages exist; DPO/retention and photo-access commitments remain unresolved.'],
      ['FAIL','Most expensive endpoint protection','Mandatory upload gate and project byte/work reservations are not live; read egress still needs protection.'],
      ['FAIL','All write validation','Prepared database bounds and full live write matrix pending.'],
      ['FAIL','Administrator force logout','No admin session-revocation workflow; local logout and account status blocks are not equivalent.'],
      ['FAIL','Data export and verified deletion','Deletion screen/function exists; export missing and hardened deletion function not live. Legal applicability requires review.'],
      ['PASS','Server emergency pause switches (local)','Upload/deletion environment flags added and tested; no general live feature-flag control panel.'],
    ]],
  ],
};
